[tool.poetry]
name = "photo-ticket-api"
version = "0.1.0"
description = ""
authors = ["Juan Ortega"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^5.0.6"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
