# Generated by Django 5.0.6 on 2024-05-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="current_images",
            field=models.IntegerField(default=0),
        ),
    ]
